services:
  nginx:
    image: nginx:1.28.3
    container_name: nginx
    restart: always
    labels:
      - mylabels.directory=${DIRECTORY:?Missing variable DIRECTORY}
      - mylabels.location=${LOCATION:?Missing variable LOCATION}